import { z } from "zod"

import { widgetSizeSchema } from "./dashboard.ts"
import { slugSchema } from "./routine.ts"

/**
 * The `widget:` frontmatter block a skill adds to its SKILL.md to opt into
 * the catalog (ADR-0006). Skills without it are not routine-capable.
 */
export const widgetMetaSchema = z.object({
  /** One-line description of what the artifact shows. */
  artifact: z.string().min(1),
  sizes: z.object({
    default: widgetSizeSchema,
    min: widgetSizeSchema.optional(),
  }),
  /** Suggested default cron schedule (5-field). */
  schedule: z.string().min(1),
})

export const catalogSkillSchema = z.object({
  /** Skill directory name; what routines.yaml's `skill:` field references. */
  id: slugSchema,
  name: z.string().min(1),
  description: z.string().min(1),
  widget: widgetMetaSchema,
})

/**
 * Shape of catalog/skills.json in the shared repo. Generated by
 * `pnpm gen:catalog` — never hand-edited. Deterministic (skills sorted by
 * id, no timestamp) so regeneration is a no-op when nothing changed.
 */
export const catalogFileSchema = z.object({
  skills: z.array(catalogSkillSchema),
})

export type WidgetMeta = z.infer<typeof widgetMetaSchema>
export type CatalogSkill = z.infer<typeof catalogSkillSchema>
export type CatalogFile = z.infer<typeof catalogFileSchema>
