/* GENERATED by scripts/gen-artifact-tokens.ts — do not edit.
   Source: apps/web/app/lib/theme.ts, the "gruvbox-dark" row (Gruvbox Dark).
   Regenerate with: node scripts/gen-artifact-tokens.ts */

/**
 * The anchor palette, keyed by token name without the `--color-` prefix.
 *
 * What a chart paints **at rest**. The board still appends
 * `artifactThemeStyle()` over the published file, and the chart's own CSS
 * layer re-points these through the same `--color-*` variables, so a viewer
 * on another theme sees their theme — see `chart/conform.ts`, which is what
 * holds every emitted colour inside this set.
 */
export const PALETTE = {
  bg: "#282828",
  bg1: "#1b1b1b",
  bg2: "#32302f",
  bg3: "#45403d",
  border: "#5a524c",
  "border-dim": "#45403d",
  ink: "#d4be98",
  "ink-dim": "#a89984",
  "ink-faint": "#928374",
  orange: "#fe8019",
  "orange-deep": "#c75117",
  yellow: "#d8a657",
  green: "#a9b665",
  aqua: "#89b482",
  blue: "#7daea3",
  purple: "#d3869b",
  red: "#ea6962",
} as const

export type PaletteName = keyof typeof PALETTE
