/**
 * Generate every static identity asset from the one geometry (ADR-0052).
 *
 * Run `node scripts/gen-brand.ts`; CI re-runs it and fails if the working
 * tree moves, so none of the output is ever hand-edited. That check is the
 * whole point of the script. The bow tie used to exist as six independent
 * copies of the same path data — `logo.tsx`, `favicon.svg`,
 * `scripts/icon.svg`, `scripts/icon-maskable.svg` and both wordmarks — each
 * carrying a comment asking the next editor to keep them in sync by hand.
 * They are now all renders of `apps/web/app/lib/mark.ts`, so "keep in sync"
 * stopped being a rule anyone can forget.
 *
 * Writes:
 *   brand/                    the distributable kit (see brand/README.md)
 *   apps/web/public/favicon.svg, wordmark-{light,dark}.svg
 *   templates/data-repo/.github/wordmark-{light,dark}.svg
 *   scripts/icon.svg, scripts/icon-maskable.svg   (raster sources)
 *
 * Rasters are NOT written here: `scripts/render-icons.sh` drives them through
 * headless Chrome, because ImageMagick's SVG delegate is not faithful to the
 * gradients and filters.
 */
import { mkdirSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import {
  CHIP_RADIUS,
  CHIP_VIEWBOX,
  GLYPH_VIEWBOX,
  KNOT,
  LOGOTYPE,
  WING_GRADIENT,
  WING_L,
  WING_R,
  WORDMARK_VIEWBOX,
} from "../apps/web/app/lib/mark.ts"
import { MARK_IDENTITY } from "../apps/web/app/lib/theme.ts"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const written: string[] = []

function emit(rel: string, body: string): void {
  const file = path.join(root, rel)
  mkdirSync(path.dirname(file), { recursive: true })
  writeFileSync(file, body.trimStart())
  written.push(rel)
}

type Mode = "light" | "dark"

const NOTE = (what: string) =>
  `<!-- ${what}. Generated by scripts/gen-brand.ts from apps/web/app/lib/mark.ts — do not edit. -->`

/** Static SVGs carry explicit width/height: favicon renderers otherwise assume 300x150 and crop. */
function svg(
  viewBox: string,
  w: number,
  h: number,
  body: string,
  note: string,
): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${viewBox}">
  ${note}
${body}
</svg>
`
}

/** The three shapes in one flat tone — foreign ground, so no gradient. */
function glyphFlat(wing: string, knot: string): string {
  return `  <path d="${WING_L}" fill="${wing}"/>
  <path d="${WING_R}" fill="${wing}"/>
  <path d="${KNOT}" fill="${knot}"/>`
}

/** The fold gradient, per wing — only ever used where the mark owns its tile. */
function foldDefs(mode: Mode, suffix = ""): string {
  const m = MARK_IDENTITY[mode]
  const ramp = (
    id: string,
    g: { x1: number; y1: number; x2: number; y2: number },
  ) =>
    `    <linearGradient id="${id}${suffix}" gradientUnits="userSpaceOnUse" x1="${g.x1}" y1="${g.y1}" x2="${g.x2}" y2="${g.y2}">
      <stop offset="0" stop-color="${m.wingTip}"/><stop offset=".55" stop-color="${m.wingTip}"/><stop offset="1" stop-color="${m.wingFold}"/>
    </linearGradient>`
  return `${ramp("wl", WING_GRADIENT.left)}
${ramp("wr", WING_GRADIENT.right)}`
}

/**
 * The product-icon chip: the mark on a tile it owns — top-lit, bordered, its
 * own contact shadow under it. `bleed` drops the rounding and the border for
 * the maskable variant, where the launcher supplies the mask.
 */
function chip(
  mode: Mode,
  opts: { bleed?: boolean; scale?: number } = {},
): string {
  const m = MARK_IDENTITY[mode]
  const r = opts.bleed ? 0 : CHIP_RADIUS
  const inner = opts.bleed
    ? // 0.82 about centre keeps the bow inside the ~80% safe zone under any
      // circle or squircle crop.
      `  <g transform="translate(32 32) scale(0.82) translate(-32 -32)">
${shadowAndTie(mode)}
  </g>`
    : shadowAndTie(mode)
  return `  <defs>
    <linearGradient id="tile" gradientUnits="userSpaceOnUse" x1="32" y1="0" x2="32" y2="64">
      <stop offset="0" stop-color="${m.tileTop}"/><stop offset="1" stop-color="${m.tileBottom}"/>
    </linearGradient>
${foldDefs(mode)}
    <clipPath id="cc"><rect width="64" height="64" rx="${r}"/></clipPath>
    <filter id="cs" x="-30%" y="-30%" width="160%" height="160%"><feGaussianBlur stdDeviation=".85"/></filter>
  </defs>
  <rect width="64" height="64" rx="${r}" fill="url(#tile)"/>
${inner}${
    opts.bleed
      ? ""
      : `\n  <rect x=".55" y=".55" width="62.9" height="62.9" rx="${CHIP_RADIUS - 0.55}" fill="none" stroke="${m.tileBorder}" stroke-width="1"/>`
  }`
}

function shadowAndTie(mode: Mode): string {
  const m = MARK_IDENTITY[mode]
  return `  <g clip-path="url(#cc)" filter="url(#cs)" opacity="0.24" transform="translate(0 1)">
    <path d="${WING_L}" fill="#000"/><path d="${WING_R}" fill="#000"/><path d="${KNOT}" fill="#000"/>
  </g>
  <path d="${WING_L}" fill="url(#wl)"/>
  <path d="${WING_R}" fill="url(#wr)"/>
  <path d="${KNOT}" fill="${m.knot}"/>`
}

// ─────────────────────────────────────────────────────────── the brand kit
const SIZES = { mark: [48, 26], chip: [64, 64], wordmark: [300, 64] } as const

for (const mode of ["light", "dark"] as const) {
  const m = MARK_IDENTITY[mode]
  emit(
    `brand/mark/steward-mark-${mode}.svg`,
    svg(
      GLYPH_VIEWBOX,
      ...SIZES.mark,
      glyphFlat(m.wingFlat, m.knot),
      NOTE(`Steward mark, ${mode} colourway`),
    ),
  )
  emit(
    `brand/icon/steward-icon-${mode}.svg`,
    svg(
      CHIP_VIEWBOX,
      ...SIZES.chip,
      chip(mode),
      NOTE(`Steward product icon, ${mode} colourway`),
    ),
  )
  emit(
    `brand/wordmark/steward-wordmark-${mode}.svg`,
    svg(
      WORDMARK_VIEWBOX,
      ...SIZES.wordmark,
      `${chip(mode)}\n  <path d="${LOGOTYPE}" fill="${mode === "dark" ? MARK_IDENTITY.dark.knot : "#282828"}"/>`,
      NOTE(`Steward wordmark, ${mode} colourway`),
    ),
  )
}

/**
 * One-colour cuts: a press, an embroidery file, a partner's slide, a laser —
 * anywhere the mark gets exactly one ink and no second colour to spend.
 *
 * The cut is the **solid silhouette**, all three shapes in one ink, and that
 * is a decision rather than the lazy option. Knocking the knot out to the
 * ground was tried first and it severs the mark: the knot is 14 tall and the
 * waist it covers is only 8, so the hole eats the whole join and leaves two
 * disconnected wedges that read as a bird, not a bow. Solid, the pinch at the
 * waist carries the read on its own — which is exactly what the squint and
 * single-colour tests were for.
 *
 * So the knot is a *colour relationship*, not a shape the outline depends on.
 * At one ink it simply stops being drawn, and nothing is lost.
 */
for (const [name, ink] of [
  ["black", "#000000"],
  ["white", "#ffffff"],
] as const) {
  const tie = (indent = "  ") =>
    [WING_L, WING_R, KNOT]
      .map((d) => `${indent}<path d="${d}" fill="${ink}"/>`)
      .join("\n")
  emit(
    `brand/mark/steward-mark-${name}.svg`,
    svg(
      GLYPH_VIEWBOX,
      ...SIZES.mark,
      tie(),
      NOTE(`Steward mark, single colour (${name}) — solid silhouette`),
    ),
  )
  emit(
    `brand/wordmark/steward-wordmark-${name}.svg`,
    svg(
      WORDMARK_VIEWBOX,
      ...SIZES.wordmark,
      `${tie()}\n  <path d="${LOGOTYPE}" fill="${ink}"/>`,
      NOTE(`Steward wordmark, single colour (${name}) — solid silhouette`),
    ),
  )
}

/** Colour-scheme-reactive cuts: one file that serves both modes. Flat fills —
 *  the fold is invisible at favicon sizes, and these are what a `<picture>`
 *  or a raw `<img>` reaches for when it cannot know the viewer's mode. */
function autoStyle(
  sel: (m: typeof MARK_IDENTITY.light) => Record<string, string>,
): string {
  const rule = (m: typeof MARK_IDENTITY.light) =>
    Object.entries(sel(m))
      .map(([k, v]) => `${k}{${v}}`)
      .join("")
  return `  <style>
    ${rule(MARK_IDENTITY.light)}
    @media (prefers-color-scheme:dark){${rule(MARK_IDENTITY.dark)}}
  </style>`
}

const autoBody = `${autoStyle((m) => ({
  ".wing": `fill:${m.wingFlat}`,
  ".knot": `fill:${m.knot}`,
}))}
  <path class="wing" d="${WING_L}"/>
  <path class="wing" d="${WING_R}"/>
  <path class="knot" d="${KNOT}"/>`

emit(
  "brand/mark/steward-mark-auto.svg",
  svg(
    GLYPH_VIEWBOX,
    ...SIZES.mark,
    autoBody,
    NOTE("Steward mark, follows the viewer's colour scheme"),
  ),
)

const faviconBody = `${autoStyle((m) => ({
  ".tile": `fill:${m.tileTop}`,
  ".bd": `stroke:${m.tileBorder}`,
  ".wing": `fill:${m.wingFlat}`,
  ".knot": `fill:${m.knot}`,
}))}
  <rect class="tile" width="64" height="64" rx="${CHIP_RADIUS}"/>
  <path class="wing" d="${WING_L}"/>
  <path class="wing" d="${WING_R}"/>
  <path class="knot" d="${KNOT}"/>
  <rect class="bd" x=".55" y=".55" width="62.9" height="62.9" rx="${CHIP_RADIUS - 0.55}" fill="none" stroke-width="1"/>`

for (const rel of [
  "brand/icon/steward-icon-auto.svg",
  "apps/web/public/favicon.svg",
]) {
  emit(
    rel,
    svg(
      CHIP_VIEWBOX,
      ...SIZES.chip,
      faviconBody,
      NOTE(
        "Steward product icon, follows the viewer's colour scheme. Flat fills: the fold gradient is invisible at 16px",
      ),
    ),
  )
}

/** The maskable adaptive icon: full-bleed, opaque, bow inside the safe zone. */
for (const rel of [
  "brand/icon/steward-icon-maskable.svg",
  "scripts/icon-maskable.svg",
]) {
  emit(
    rel,
    svg(
      CHIP_VIEWBOX,
      ...SIZES.chip,
      chip("dark", { bleed: true }),
      NOTE("Steward maskable adaptive icon (dark, full-bleed)"),
    ),
  )
}

/** Launcher source: rounded on transparent, so iOS and Android re-mask it.
 *  The .ico and the launcher rasters cannot media-query, so they bake dark. */
emit(
  "scripts/icon.svg",
  svg(
    CHIP_VIEWBOX,
    ...SIZES.chip,
    chip("dark"),
    NOTE("Steward launcher icon source (dark identity chip)"),
  ),
)

/** The README lockups, swapped by prefers-color-scheme in a <picture>, and
 *  mirrored into every data repo's .github/ (built-in template + team repos). */
for (const mode of ["light", "dark"] as const) {
  const body = `${chip(mode)}\n  <path d="${LOGOTYPE}" fill="${mode === "dark" ? MARK_IDENTITY.dark.knot : "#282828"}"/>`
  const doc = svg(
    WORDMARK_VIEWBOX,
    ...SIZES.wordmark,
    body,
    NOTE(`Steward wordmark, ${mode}`),
  ).replace("<svg ", `<svg role="img" aria-label="Steward" `)
  emit(`apps/web/public/wordmark-${mode}.svg`, doc)
  emit(`templates/data-repo/.github/wordmark-${mode}.svg`, doc)
}

/** The identity, machine-readable — for anyone theming around the mark. */
emit(
  "brand/palette/identity.json",
  `${JSON.stringify(
    {
      $comment:
        "Steward's fixed identity. Generated by scripts/gen-brand.ts. Drawn from the gruvbox rows of the theme registry; the mark never follows the active theme.",
      law: "The gradient is a privilege of owning the ground — the chip carries the fold, the bare glyph goes flat.",
      light: MARK_IDENTITY.light,
      dark: MARK_IDENTITY.dark,
    },
    null,
    2,
  )}\n`,
)

console.log(`gen-brand: wrote ${written.length} files`)
for (const f of written) console.log(`  ${f}`)
