/**
 * Generate every static identity asset from the one geometry (ADR-0052/0053).
 *
 * Run `node scripts/gen-brand.ts`; CI re-runs it and fails if the working
 * tree moves, so none of the output is ever hand-edited. That check is the
 * whole point of the script. The bow tie used to exist as six independent
 * copies of the same path data, each carrying a comment asking the next
 * editor to keep them in sync by hand. They are now all renders of
 * `apps/web/app/lib/mark.ts`.
 *
 * Writes:
 *   brand/                    the distributable kit (see brand/README.md)
 *   apps/web/public/favicon.svg, wordmark-{light,dark}.svg
 *   templates/data-repo/.github/wordmark-{light,dark}.svg
 *   scripts/icon.svg, scripts/icon-maskable.svg   (raster sources)
 *
 * Rasters are NOT written here: `scripts/render-icons.sh` drives them through
 * headless Chrome, because ImageMagick's SVG delegate is not faithful to the
 * gradients.
 *
 * ## Two framings, and one of them stopped switching
 *
 * The **bare glyph** is mode-keyed: it sits on a surface it does not own, so
 * it takes the light or dark ember. The **chip** is a single colourway in both
 * modes (ADR-0053) — it is a saturated object rather than a surface, and
 * making it follow the viewer's mode produced a polarity flip that read as two
 * different logos. That is why `favicon.svg` no longer carries a
 * `prefers-color-scheme` block, and why there is one `steward-icon.svg`
 * instead of a light, a dark and an auto.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import {
  CHIP_INSET,
  chipTransform,
  CHIP_TILT,
  CHIP_VIEWBOX,
  drawnFeatures,
  glyphViewBox,
  KNOT,
  LOGOTYPE,
  MARK_BUTTONS,
  MARK_MINIMUM,
  MARK_RATIOS,
  MARK_TILE,
  markSpan,
  MASK_FILL,
  MASK_INSET,
  MASK_SAFE,
  squirclePath,
  WING_L,
  WING_R,
  WORDMARK_VIEWBOX,
} from "../apps/web/app/lib/mark.ts"
import {
  CHIP_IDENTITY,
  LOGOTYPE_INK,
  MARK_IDENTITY,
  themeEntries,
} from "../apps/web/app/lib/theme.ts"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const written: string[] = []

function emit(rel: string, body: string): void {
  const file = path.join(root, rel)
  mkdirSync(path.dirname(file), { recursive: true })
  writeFileSync(file, body.trimStart())
  written.push(rel)
}

const NOTE = (what: string) =>
  `<!-- ${what}. Generated by scripts/gen-brand.ts from apps/web/app/lib/mark.ts — do not edit. -->`

/**
 * Rewrite a marked region inside a hand-written file.
 *
 * The prose around the mark stays human; the numbers in it do not. Every
 * measured claim — hexes, contrast ratios, the size each ratio lands at — used
 * to be typed into `DESIGN.md`, `brand/README.md` and the ADR separately, and
 * the one that mattered ("validated down to 16px… floor 4.30:1… zero
 * failures") was still sitting there being false while the favicon was
 * illegible. ADR-0052 made "keep in sync" a check for the geometry; this is
 * the same check for the prose (ADR-0054).
 */
function replaceRegion(rel: string, key: string, body: string): void {
  const file = path.join(root, rel)
  // MDX has no HTML comments — `<!--` is a parse error there, not a comment,
  // so the markers take the JSX-expression form in `.mdx` and the HTML form in
  // plain markdown. Worth knowing rather than guessing: both docs pages failed
  // to compile the first time this ran, and only loading the route said so.
  const mdx = rel.endsWith(".mdx")
  const wrap = (text: string) => (mdx ? `{/* ${text} */}` : `<!-- ${text} -->`)
  const open = wrap(`gen:${key}`)
  const close = wrap(`/gen:${key}`)
  const current = readFileSync(file, "utf8")
  const from = current.indexOf(open)
  const to = current.indexOf(close)
  if (from === -1 || to === -1) {
    throw new Error(`${rel}: missing ${open} … ${close} markers`)
  }
  const next =
    current.slice(0, from + open.length) +
    `\n${wrap("Generated by scripts/gen-brand.ts — do not edit by hand.")}\n\n${body.trim()}\n\n` +
    current.slice(to)
  if (next !== current) writeFileSync(file, next)
  written.push(`${rel} (${key})`)
}

function luminance(hex: string): number {
  const v = Number.parseInt(hex.slice(1), 16)
  const channel = (c: number) => {
    const s = c / 255
    return s <= 0.04045 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4
  }
  return (
    0.2126 * channel((v >> 16) & 0xff) +
    0.7152 * channel((v >> 8) & 0xff) +
    0.0722 * channel(v & 0xff)
  )
}

function contrast(a: string, b: string): string {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return ((hi + 0.05) / (lo + 0.05)).toFixed(2)
}

/**
 * Worst case for a tone across the surfaces it is actually asked to hold.
 *
 * `mode` scopes it: the bare glyph is keyed on mode, so the light ember only
 * ever lands on a light theme's surfaces and measuring it against a dark
 * theme's page answers a question nobody asked. The chip takes no mode, and
 * faces all of them.
 */
function worstGround(
  hex: string,
  mode?: "light" | "dark",
): { ratio: string; where: string } {
  let worst = { ratio: Number.POSITIVE_INFINITY, where: "" }
  for (const [name, theme] of themeEntries) {
    if (mode && theme.mode !== mode) continue
    for (const [tier, surface] of [
      ["page", theme.tokens.bg],
      ["card", theme.tokens.bg1],
    ] as const) {
      const r = Number(contrast(hex, surface))
      if (r < worst.ratio) worst = { ratio: r, where: `${name} ${tier}` }
    }
  }
  return { ratio: worst.ratio.toFixed(2), where: worst.where }
}

/**
 * A markdown table, already padded the way the formatter would pad it.
 *
 * Not cosmetic. `oxfmt` aligns table columns to their widest cell; a generator
 * that emits them unpadded and a formatter that pads them rewrite each other
 * forever, and CI — which runs both and then fails on a dirty tree — would
 * never go green. Emitting the canonical form is what makes the generated
 * region a fixed point.
 */
function table(header: string[], rows: string[][]): string {
  const all = [header, ...rows]
  const width = header.map((_, i) =>
    Math.max(...all.map((r) => (r[i] ?? "").length)),
  )
  const line = (cells: string[]) =>
    `| ${cells.map((c, i) => (c ?? "").padEnd(width[i])).join(" | ")} |`
  return [
    line(header),
    `| ${width.map((w) => "-".repeat(Math.max(w, 3))).join(" | ")} |`,
    ...rows.map(line),
  ].join("\n")
}

/** The tab strips and forge backgrounds the chip actually lands on. */
const HABITAT: [string, string][] = [
  ["Chrome, light", "#dee1e6"],
  ["Chrome, dark", "#202124"],
  ["GitHub, light", "#ffffff"],
  ["GitHub, dark", "#0d1117"],
]

/** Static SVGs carry explicit width/height: favicon renderers otherwise assume 300x150 and crop. */
function svg(
  viewBox: string,
  w: number,
  h: number,
  body: string,
  note: string,
): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${viewBox}">
  ${note}
${body}
</svg>
`
}

/**
 * The mark's ink: two folded wings, a square knot, two buttons (ADR-0055), all
 * carrying the one attribute — a `fill="…"` or a `class="…"` for the auto cut.
 */
function markBody(attr: string, opts: { buttons?: boolean } = {}): string {
  const withButtons = opts.buttons ?? true
  const buttons = withButtons
    ? "\n" +
      MARK_BUTTONS.map(
        (b) => `  <circle ${attr} cx="${b.cx}" cy="${b.cy}" r="${b.rad}"/>`,
      ).join("\n")
    : ""
  return `  <path ${attr} d="${WING_L}"/>
  <path ${attr} d="${WING_R}"/>
  <path ${attr} d="${KNOT}"/>${buttons}`
}

/** The bare glyph: the mark in one flat ink, level. */
function glyph(fill: string, cls?: string): string {
  return markBody(cls ? `class="${cls}"` : `fill="${fill}"`)
}

const TILE = squirclePath()

/**
 * How the mark is centred inside a lockup's leading slot. It is `chipTransform`
 * without the tile — the whole mark (bow, knot, buttons), scaled about its own
 * centre and dropped on the tile centre — so the lockup mark and the chip are
 * placed by the same rule.
 */
const LOCK_SCALE = 1.1
function lockupMark(fill: string): string {
  return `  <g transform="${chipTransform(LOCK_SCALE)}">
${markBody(`fill="${fill}"`)}
  </g>`
}

/**
 * The product-icon chip: a **flat ember** superellipse tile with the bow cut
 * out of it in cream (ADR-0055). No gradient — the flat #c75117 clears every
 * ground the chip lands on by itself, so the diagonal the old two-stop tile
 * needed is gone, and the chip is one drawing at every size.
 *
 * `bleed` squares the corners and scales the artwork for the maskable variant,
 * where the launcher supplies its own mask and crops ~20%. The placement is
 * `chipTransform`'s, so the app's hero chip and the favicon are one drawing.
 */
function chip(opts: { bleed?: boolean; buttons?: boolean } = {}): string {
  const { tile, bow } = CHIP_IDENTITY
  const tileShape = opts.bleed
    ? `  <rect width="64" height="64" fill="${tile}"/>`
    : `  <path d="${TILE}" fill="${tile}"/>`
  return `${tileShape}
  <g transform="${chipTransform(opts.bleed ? MASK_INSET : CHIP_INSET)}">
${markBody(`fill="${bow}"`, { buttons: opts.buttons })}
  </g>`
}

// ─────────────────────────────────────────────────────────── the brand kit
const GLYPH_BOX = glyphViewBox()
const GLYPH_SIZE: [number, number] = [
  Number(GLYPH_BOX.split(" ")[2]),
  Number(GLYPH_BOX.split(" ")[3]),
]
const CHIP_SIZE: [number, number] = [64, 64]
const WORDMARK_SIZE: [number, number] = [300, 64]

for (const mode of ["light", "dark"] as const) {
  emit(
    `brand/mark/steward-mark-${mode}.svg`,
    svg(
      GLYPH_BOX,
      ...GLYPH_SIZE,
      glyph(MARK_IDENTITY[mode].ink),
      NOTE(`Steward mark, ${mode} colourway`),
    ),
  )
  emit(
    `brand/wordmark/steward-wordmark-${mode}.svg`,
    svg(
      WORDMARK_VIEWBOX,
      ...WORDMARK_SIZE,
      `${lockupMark(MARK_IDENTITY[mode].ink)}\n  <path d="${LOGOTYPE}" fill="${LOGOTYPE_INK[mode]}"/>`,
      NOTE(`Steward wordmark, ${mode} colourway`),
    ),
  )
}

/** The chip is one colourway, so there is exactly one of it. */
emit(
  "brand/icon/steward-icon.svg",
  svg(CHIP_VIEWBOX, ...CHIP_SIZE, chip(), NOTE("Steward product icon")),
)

/**
 * One-colour cuts: a press, an embroidery file, a partner's slide, a laser —
 * anywhere the mark gets exactly one ink and no second colour to spend.
 *
 * Nothing special is needed any more. This used to be a decision, because
 * knocking the knot out to the ground severed the mark into two wedges, so
 * the cut had to stop drawing the knot. The mark is one shape at every ink
 * now, so the one-colour cut is simply the mark.
 */
for (const [name, ink] of [
  ["black", "#000000"],
  ["white", "#ffffff"],
] as const) {
  emit(
    `brand/mark/steward-mark-${name}.svg`,
    svg(
      GLYPH_BOX,
      ...GLYPH_SIZE,
      glyph(ink),
      NOTE(`Steward mark, single colour (${name})`),
    ),
  )
  emit(
    `brand/wordmark/steward-wordmark-${name}.svg`,
    svg(
      WORDMARK_VIEWBOX,
      ...WORDMARK_SIZE,
      // The mark takes the lockup's placement, the same one the coloured
      // lockups beside it in the kit use.
      `${lockupMark(ink)}\n  <path d="${LOGOTYPE}" fill="${ink}"/>`,
      NOTE(`Steward wordmark, single colour (${name})`),
    ),
  )
}

/**
 * The bare glyph following the viewer's colour scheme — the one cut that
 * still needs to, since it has no tile and lands on an unknown surface.
 */
emit(
  "brand/mark/steward-mark-auto.svg",
  svg(
    GLYPH_BOX,
    ...GLYPH_SIZE,
    `  <style>
    .ink{fill:${MARK_IDENTITY.light.ink}}
    @media (prefers-color-scheme:dark){.ink{fill:${MARK_IDENTITY.dark.ink}}}
  </style>
${glyph("", "ink")}`,
    NOTE("Steward mark, follows the viewer's colour scheme"),
  ),
)

/**
 * The launcher/app-icon source — full mark, buttons and all, rendered to the
 * 180/192/512 PNGs. One flat colourway, so no media query: the ember tile holds
 * its own against a light or a dark tab strip (ADR-0055).
 */
emit(
  "scripts/icon.svg",
  svg(
    CHIP_VIEWBOX,
    ...CHIP_SIZE,
    chip(),
    NOTE("Steward product icon — one colourway, both modes"),
  ),
)

/**
 * The browser tab, and the source the `.ico` is rasterised from. Same drawing
 * as the app icon — the buttons clear a device pixel even at 16px (1.2px), so
 * the tab keeps them.
 */
emit(
  "apps/web/public/favicon.svg",
  svg(
    CHIP_VIEWBOX,
    ...CHIP_SIZE,
    chip(),
    NOTE("Steward browser-tab icon — one colourway, both modes"),
  ),
)

/** The maskable adaptive icon: full-bleed, bow inside the safe zone. */
for (const rel of [
  "brand/icon/steward-icon-maskable.svg",
  "scripts/icon-maskable.svg",
]) {
  emit(
    rel,
    svg(
      CHIP_VIEWBOX,
      ...CHIP_SIZE,
      chip({ bleed: true }),
      NOTE("Steward maskable adaptive icon (full-bleed)"),
    ),
  )
}

/** The README lockups, swapped by prefers-color-scheme in a <picture>, and
 *  mirrored into every data repo's .github/ (built-in template + team repos). */
for (const mode of ["light", "dark"] as const) {
  const doc = svg(
    WORDMARK_VIEWBOX,
    ...WORDMARK_SIZE,
    `${lockupMark(MARK_IDENTITY[mode].ink)}\n  <path d="${LOGOTYPE}" fill="${LOGOTYPE_INK[mode]}"/>`,
    NOTE(`Steward wordmark, ${mode}`),
  ).replace("<svg ", `<svg role="img" aria-label="Steward" `)
  emit(`apps/web/public/wordmark-${mode}.svg`, doc)
  emit(`templates/data-repo/.github/wordmark-${mode}.svg`, doc)
}

/** The identity, machine-readable — for anyone theming around the mark. */
emit(
  "brand/palette/identity.json",
  `${JSON.stringify(
    {
      $comment:
        "Steward's fixed identity. Generated by scripts/gen-brand.ts. Drawn from the brand palette (ADR-0055); the mark never follows the active theme.",
      law: "The bow is a real bow tie — two wings, a knot, two buttons — in one neutral ink, keyed on mode. The ember lives on the chip, a flat single colourway in both modes.",
      glyph: { light: MARK_IDENTITY.light, dark: MARK_IDENTITY.dark },
      chip: CHIP_IDENTITY,
      logotype: LOGOTYPE_INK,
    },
    null,
    2,
  )}\n`,
)

// ───────────────────────────────────────── the measured claims, as markdown

const glyphWorst = {
  light: worstGround(MARK_IDENTITY.light.ink, "light"),
  dark: worstGround(MARK_IDENTITY.dark.ink, "dark"),
}
const tileWorst = worstGround(CHIP_IDENTITY.tile)

const facts = `
### The identity

${table(
  ["", "hex", ""],
  [
    [
      "bare glyph, light surfaces",
      `\`${MARK_IDENTITY.light.ink}\``,
      "brand ink",
    ],
    [
      "bare glyph, dark surfaces",
      `\`${MARK_IDENTITY.dark.ink}\``,
      "gruvbox-light `bg`",
    ],
    ["chip tile", `\`${CHIP_IDENTITY.tile}\``, "gruvbox `accentDeep`"],
    [
      "the bow, cut out of the tile",
      `\`${CHIP_IDENTITY.bow}\``,
      "gruvbox-light `bg`",
    ],
    ["logotype, light lockup", `\`${LOGOTYPE_INK.light}\``, "brand ink"],
    ["logotype, dark lockup", `\`${LOGOTYPE_INK.dark}\``, "gruvbox-light `bg`"],
  ],
)}

### What is measured, and where it is worst

The bare glyph is a single ink, so it has exactly one boundary: itself against
the surface it was handed. Each colourway is measured only against the surfaces
it can actually land on — page and card, of every theme in its mode. Neutral
ink clears its ground with enormous room, which is the point of moving the
colour off the bow:

${table(
  ["", "worst", "on"],
  [
    [
      "glyph on light surfaces",
      `**${glyphWorst.light.ratio}:1**`,
      glyphWorst.light.where,
    ],
    [
      "glyph on dark surfaces",
      `**${glyphWorst.dark.ratio}:1**`,
      glyphWorst.dark.where,
    ],
  ],
)}

The chip takes no mode, so its **flat** tile faces all ${themeEntries.length} themes at once. There
is no gradient stop to fail on one ground and clear on another — the single
ember carries the edge, and it clears the graphics floor on every surface it
lands on:

${table(
  ["", "worst", "on"],
  [["chip tile", `${tileWorst.ratio}:1`, tileWorst.where]],
)}

The chip's own interior edge, and its habitat — the surfaces it lands on that
are not Steward's:

${table(
  ["", "ratio"],
  [
    [
      "bow against the tile",
      `${contrast(CHIP_IDENTITY.bow, CHIP_IDENTITY.tile)}:1`,
    ],
    ...HABITAT.map(([name, bg]) => [
      `tile on ${name}`,
      `${contrast(CHIP_IDENTITY.tile, bg)}:1`,
    ]),
  ],
)}

### Every drawn feature at the declared minimum

Device pixels at 1×. A feature either survives here or is not drawn — held by
\`mark.test.ts\`. The fold (\`notch\`, \`puff\`) is absent: it modulates the wing's
edge rather than drawing a region with a width, exactly as the old \`sweep\` did.

${table(
  [
    "ratio",
    "units",
    `chip @ ${MARK_MINIMUM.chip}px`,
    `glyph @ ${MARK_MINIMUM.glyph}px`,
  ],
  Object.entries(drawnFeatures()).map(([name, units]) => [
    `\`${name}\``,
    String(units),
    `${(units * (MARK_MINIMUM.chip / markSpan("chip"))).toFixed(2)}px`,
    `${(units * (MARK_MINIMUM.glyph / markSpan("glyph"))).toFixed(2)}px`,
  ]),
)}

### How the chip places it

The bow is ${MARK_RATIOS.bowW} × ${MARK_RATIOS.bowH} units at an aspect of ${(MARK_RATIOS.bowW / MARK_RATIOS.bowH).toFixed(2)}:1 — ${((MARK_RATIOS.bowW / MARK_TILE) * 100).toFixed(0)}% of the tile's width.
Every chip insets the **whole mark** — bow, knot and buttons — through one
function; the chip keeps a hair of ground, and the maskable fills more of its
safe zone so the full-bleed square reads bold:

${table(
  ["", "scale", "bow spans", "of the visible tile", "ground per side"],
  [
    [
      "chip",
      `\`CHIP_INSET\` ${CHIP_INSET}`,
      `${(MARK_RATIOS.bowW * CHIP_INSET).toFixed(1)}u`,
      `${(((MARK_RATIOS.bowW * CHIP_INSET) / MARK_TILE) * 100).toFixed(0)}%`,
      `${((MARK_TILE - MARK_RATIOS.bowW * CHIP_INSET) / 2).toFixed(1)}u`,
    ],
    [
      "maskable icon",
      `\`MASK_INSET\` ${MASK_INSET.toFixed(3)}`,
      `${(MARK_RATIOS.bowW * MASK_INSET).toFixed(1)}u`,
      `${(((MARK_RATIOS.bowW * MASK_INSET) / (MARK_TILE * MASK_SAFE)) * 100).toFixed(0)}%`,
      `${((MARK_TILE * MASK_SAFE - MARK_RATIOS.bowW * MASK_INSET) / 2).toFixed(1)}u`,
    ],
  ],
)}

The maskable column measures against the safe zone — the middle ${(MASK_SAFE * 100).toFixed(0)}% a launcher
is guaranteed to show. Its bow fills ${(MASK_FILL * 100).toFixed(0)}% of that zone, bolder than the chip's
share of its tile so the full-bleed square does not read small, and kept off the
mask so a launcher's crop never reaches the tips.

The bow is **level in every framing** (\`CHIP_TILT\` ${CHIP_TILT}°): it is symmetric by
construction and the tile is square, so a rotation fights both.
`

/**
 * The palette, measured. Lives here rather than in its own script because CI
 * runs this one and fails on a dirty tree, and a second generator wired into
 * nothing is a generator that silently stops running (ADR-0054).
 */
const FLOORS: [string, string][] = [
  ["`ink` on every surface", "4.5:1 — body copy, full AA"],
  [
    "`inkDim` on every surface",
    "4.5:1 — no dimmer text tier exists (ADR-0048)",
  ],
  ["`inkFaint` on every surface", "3:1 — a glyph role, WCAG 1.4.11"],
  [
    "`borderStrong` on page and card",
    "3:1 — fill-less controls are only their edge",
  ],
  ["`border` on page and card", "1.5:1 — object edges"],
  ["`borderDim` on page and card", "1.2:1 — plane hairlines"],
  ["`bg` against `bg1`", "1.05:1 — a card must sit off the page"],
]

const palette = `
### The tiers

Every theme carries the same roles, and every role is held to the same floor on
every theme. The floors are asserted in \`theme.test.ts\`, per theme, so a new
palette cannot ship a tier that inverts or a surface that vanishes.

${table(
  ["held", "floor, and why"],
  FLOORS.map(([what, why]) => [what, why]),
)}

Two of those are ordering rather than absolute: \`inkDim\` may never out-contrast
\`ink\`, and the three border tiers must stay strictly ranked. A divider louder
than the card edge it sits inside is a hierarchy inversion, and it is the defect
every light theme drifted into before the tiers were held.

### Every theme, measured at its worst surface

\`ink\` and \`accent\` are the two that carry the most, so they are the two worth
seeing per theme. Both are shown against the harder of page and card.

${table(
  ["theme", "mode", "`ink`", "`accent`", "page", "card"],
  themeEntries.map(([name, theme]) => {
    const t = theme.tokens
    return [
      name,
      theme.mode,
      `${Math.min(Number(contrast(t.ink, t.bg)), Number(contrast(t.ink, t.bg1))).toFixed(2)}:1`,
      `${Math.min(Number(contrast(t.accent, t.bg)), Number(contrast(t.accent, t.bg1))).toFixed(2)}:1`,
      `\`${t.bg}\``,
      `\`${t.bg1}\``,
    ]
  }),
)}
`

replaceRegion(
  "apps/web/content/docs/design/color.mdx",
  "palette-facts",
  palette,
)

for (const target of [
  "DESIGN.md",
  "brand/README.md",
  "apps/web/content/docs/design/mark.mdx",
]) {
  replaceRegion(target, "mark-facts", facts)
}

console.log(`gen-brand: wrote ${written.length} files`)
for (const f of written) console.log(`  ${f}`)
