/**
 * Generate the artifact kit's Tailwind palette from the theme registry
 * (ADR-0050). Run `node scripts/gen-artifact-tokens.ts`; CI re-runs it and
 * fails if the working tree moves, so the output is never hand-edited.
 *
 * Why generated rather than written once: ADR-0007 split styling into
 * "Tailwind for chrome, raw tokens for artifacts" and accepted a standing
 * cost — "changing the palette means editing the `@theme` block *and* the
 * token snippet in the widget-artifact skill — keep them identical; a
 * lint-style check can enforce this once the skill exists." This is that
 * check, arrived at from the other direction: there is no second copy to keep
 * identical, because the kit's copy is derived from the registry.
 *
 * The emitted block is plain `@theme`, not `@theme inline`. The chrome maps
 * `--color-*` onto `--palette-*` so a `[data-theme]` swap re-themes it live;
 * an artifact has no such swap — the board appends `artifactThemeStyle()`,
 * which re-points the very same `--color-*` names with `!important`. So the
 * literal values below are only what the file paints **at rest**, opened raw
 * off the artifacts branch, and Tailwind's utilities must resolve through the
 * variables rather than inline the hexes for the override to reach them.
 * `tokens.test.ts` pins that.
 */
import { writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import {
  ARTIFACT_TOKENS,
  DEFAULT_THEME,
  themes,
} from "../apps/web/app/lib/theme.ts"

const here = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.resolve(
  here,
  "..",
  "packages",
  "artifact-kit",
  "src",
  "tokens",
  "tokens.css",
)

// Gruvbox dark is the anchor artifacts are authored in (widget-standard), not
// the fresh-install default (that is Flexoki, ADR-0046). Authoring against the
// anchor is what keeps a raw-opened artifact looking like the thing the
// routine wrote, whatever the viewer's preference happens to be.
const anchor = themes[DEFAULT_THEME]

const palette = ARTIFACT_TOKENS.map(
  ([cssVar, role]) => `  ${cssVar}: ${anchor.tokens[role]};`,
).join("\n")

const css = `/* GENERATED by scripts/gen-artifact-tokens.ts — do not edit.
   Source: apps/web/app/lib/theme.ts, the "${DEFAULT_THEME}" row (${anchor.label}).
   Regenerate with: node scripts/gen-artifact-tokens.ts */

/* \`static\` forces every variable below into the output even when no utility
   happens to reference it. Without it Tailwind tree-shakes the unused ones,
   and an artifact that never painted with, say, aqua or purple ships without
   those declarations — so a raw-opened file has no value for them, and the
   contract validator reports them missing. The palette is a contract, not a
   usage-derived set. */
@theme static {
  /* Drop Tailwind's stock palette. An artifact paints from the registry or
     not at all — an unthemed \`bg-slate-700\` would survive the board's
     override untouched and sit at a fixed color while everything around it
     followed the active theme. */
  --color-*: initial;

  /* Only the mono face is injected by the board (ADR-0031) — the fallback
     after the comma is what a raw-opened file gets. The sans stack is the
     artifact's own: ADR-0048 moved the *chrome* to one mono face and
     explicitly declined to re-render artifacts in it, so artifacts keep the
     two-family mix the contract has always specified. */
  --font-sans: system-ui, sans-serif;
  --font-mono: "Geist Mono Variable", ui-monospace, "SF Mono", Menlo, monospace;

${palette}
}

@layer base {
  :root {
    /* Not \`!important\`: artifactThemeStyle() emits its own color-scheme in a
       later block, and equal specificity means source order settles it. */
    color-scheme: ${anchor.mode};
  }
}
`

writeFileSync(OUT, css)

/**
 * The same palette as data, for `validate.mjs`.
 *
 * The validator used to hardcode this table, and it drifted: it still enforced
 * classic gruvbox (`#ebdbb2`, `#fabd2f`) long after the registry was
 * retranscribed to gruvbox-material (ADR-0048). The effect was backwards — a
 * correctly-themed artifact *failed* the publish gate while stale ones passed,
 * so every published file kept painting the pre-ADR-0048 palette when opened
 * raw. Reading generated JSON instead means the table cannot fall behind.
 *
 * JSON rather than an import because the validator runs as plain `node` in a
 * routine environment that has no `node_modules` — `theme.ts` pulls in zod.
 */
const TOKENS_JSON = path.resolve(
  here,
  "..",
  ".claude",
  "skills",
  "widget-artifact",
  "tokens.json",
)
writeFileSync(
  TOKENS_JSON,
  `${JSON.stringify(
    Object.fromEntries(
      ARTIFACT_TOKENS.map(([cssVar, role]) => [cssVar, anchor.tokens[role]]),
    ),
    null,
    2,
  )}\n`,
)

const rel = (p: string) => path.relative(path.resolve(here, ".."), p)
console.log(
  `wrote ${rel(OUT)} + ${rel(TOKENS_JSON)} — ${ARTIFACT_TOKENS.length} tokens from ${DEFAULT_THEME}`,
)
